### ISSUE TITLE
ComplexNumber Deprecated

### ISSUE THREAD

**Issue by napen123** [MathosProject/Mathos-Project#3]
The ComplexNumber type is marked as deprecated. Should a replacement be made?

**Comment by artemlos** [comment]
I think the recent version of. NET already has complex numbers. Maybe,  we could extract methods from our implementation and turn them into extension methods?

**Comment by artemlos** [comment]
Extension methods for the Complex type in. NET, that is.

**Comment by napen123** [comment]
That sounds good.
