### ISSUE TITLE
RubyInt

### ISSUE THREAD

**Issue by napen123** [MathosProject/Mathos-Project#4]
After some thinking, I think we should remove RubyInt from Mathos. RubyInt uses IronRuby so it's not too hard to add Mathos as a dependency and use it from there. Alternatively, I think we should make something just like it but for the Mathos Parser.

ping @artemlos

**Comment by artemlos** [comment]
@napen123 Do you mean removing the entire project (including the interface) or should we keep the interface and replace IronRuby with Mathos Parser?

**Comment by napen123** [comment]
We should keep the interface and just replace Ruby with the parser.
