### ISSUE TITLE
Website is Broken

### ISSUE THREAD

**Issue by napen123** [MathosProject/Mathos-Project#5]
The [website](http://mathosproject.com/) appears to be broken. I'm getting a long list of these errors across the site:

`Notice: Array to string conversion in /var/www/mathosproject.com/wp-content/themes/product/library/options/options.php on line 8`

`Notice: Array to string conversion in /var/www/mathosproject.com/wp-content/themes/product/library/options/options.php on line 14`

**Comment by artemlos** [comment]
It's now fixed.
